{
  "openapi": "3.0.4",
  "info": {
    "title": "Instagram API - Gerenciamento de Usuários",
    "description": "API REST de gerenciamento de usuários com autenticação JWT. Padrão de resposta: { status, codigo, mensagem, dados }.",
    "version": "1.0.1"
  },
  "servers": [
    {
      "url": "http://localhost:8082",
      "description": "API - Instagram"
    }
  ],
  "tags": [
    {
      "name": "usuarios",
      "description": "Operações relacionadas ao usuário"
    },
    {
      "name": "login",
      "description": "Operações de autenticação (login, logout)"
    },
    {
      "name":"posts",
      "description": "Operações relacionadas a posts"
    }
  ],
  "paths": {
    "/usuarios/posts":{
       "post": {
        "tags": [
          "posts"
        ],
        "summary": "Criar post",
        "description": "Cria um novo post para o usuário especificado.",
        "operationId": "criarPost",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CriaçãoPostRequest"
              },
              "example": {
                "imagem": "post1.jpg",
                "conteudo": "Meu novo post!"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Post criado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sucesso"
                }
              }
            }
          },
          "400": {
            "description": "Dados incompletos",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "401": {
            "description": "Token inválido ou expirado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        }
      }
    },
    "/usuarios/{id}/posts": {
      "get": {
        "tags": [
          "posts"
        ],
        "summary": "Listar posts",
        "description": "Retorna a lista de posts cadastrados.",
        "operationId": "listarPosts",
        "responses": {
          "200": {
            "description": "Posts listados com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ListagemPostsResponse"
                }
              }
            }
          },
          "401": {
            "description": "Token inválido ou expirado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "404": {
            "description": "Nenhum post encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/usuarios/login": {
      "post": {
        "tags": [
          "login"
        ],
        "summary": "Login do usuário",
        "description": "Autentica o usuário com usuário e senha, retornando token JWT.",
        "operationId": "loginUsuario",
        "requestBody": {
          "description": "Credenciais de acesso",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              },
              "example": {
                "usuario": "joao",
                "senha": "123"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Login realizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Dados incompletos",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "401": {
            "description": "Credenciais inválidas",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        }
      }
    },
    "/usuarios/logout": {
      "post": {
        "tags": [
          "login"
        ],
        "summary": "Logout do usuário",
        "description": "Encerrando a sessão do usuário e revoga acesso token JWT.",
        "operationId": "logoutUsuario",
        "responses": {
          "200": {
            "description": "Logout realizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SucessoSimples"
                }
              }
            }
          },
          "400": {
            "description": "Token não informado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "401": {
            "description": "Token inválido ou expirado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/usuarios": {
      "get": {
        "tags": [
          "usuarios"
        ],
        "summary": "Listar usuários",
        "description": "Retorna a lista de usuários cadastrados.",
        "operationId": "listarUsuarios",
        "responses": {
          "200": {
            "description": "Usuários listados com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ListagemResponse"
                }
              }
            }
          },
          "401": {
            "description": "Token inválido ou expirado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "404": {
            "description": "Nenhum usuário encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "post": {
        "tags": [
          "usuarios"
        ],
        "summary": "Cadastrar usuário",
        "description": "Cria um novo usuário no sistema.",
        "operationId": "cadastrarUsuario",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CadastroRequest"
              },
              "example": {
                "nome": "João",
                "email": "j@j.com",
                "usuario": "joao",
                "senha": "123"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Usuário cadastrado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CadastroResponse"
                }
              }
            }
          },
          "400": {
            "description": "Dados incompletos",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "405": {
            "description": "Dados inválidos",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "409": {
            "description": "Usuário já cadastrado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        }
      }
    },
    "/usuarios/{id}": {
      "get": {
        "tags": [
          "usuarios"
        ],
        "summary": "Obter dados de um usuário",
        "description": "Retorna os detalhes de um usuário específico baseado no ID fornecido.",
        "operationId": "obterUsuarioPorId",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do usuário a ser recuperado",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário encontrado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UsuarioUnicoResponse"
                }
              }
            }
          },
          "401": {
            "description": "Token inválido ou expirado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "403": {
            "description": "Acesso negado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "patch": {
        "tags": [
          "usuarios"
        ],
        "summary": "Atualizar usuário",
        "description": "Atualiza completamente os dados de um usuário pelo ID.",
        "operationId": "atualizarUsuario",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do usuário",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AtualizacaoRequest"
              },
              "example": {
                "nome": "João",
                "email": "j@j.com",
                "usuario": "joao"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Usuário atualizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AtualizacaoResponse"
                }
              }
            }
          },
          "400": {
            "description": "Dados incompletos",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "401": {
            "description": "Token inválido ou expirado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "404": {
            "description": "Usuário já existe",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "usuarios"
        ],
        "summary": "Deletar usuário",
        "description": "Remove um usuário do sistema pelo ID.",
        "operationId": "deletarUsuario",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do usuário",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário deletado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SucessoSimples"
                }
              }
            }
          },
          "401": {
            "description": "Token inválido ou expirado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          },
          "403": {
            "description": "Acesso negado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErroResponse"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "Sucesso":{
        "example": {
          "status": "sucesso",
          "codigo": "OPERACAO_SUCESSO",
          "mensagem": "Operação realizada com sucesso"
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          }
        ] 
      },
      "CriaçãoPostRequest": {
        "type": "object",
        "properties": {
          "conteudo": {
            "type": "string",
            "example": "Meu novo post!"
          }
        },
        "required": [
          "conteudo"
        ]
      },
      "ListagemPostsResponse": {
        "example": {
          "status": "sucesso",
          "codigo": "LISTAGEM_POSTS_SUCESSO",
          "mensagem": "Posts listados com sucesso",
          "dados": {
            "posts": [
              {
                "id": "1",
                "conteudo": "Meu primeiro post!",
                "data_criacao": "2024-01-01T12:00:00Z"
              }
            ]
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          }
        ]
      },
      "LogoutRequest": {
        "type": "object",
        "properties": {
          "Token": {
            "type": "string",
            "example": "eyJhbGci..."
          }
        }
      },
      "PadraoResposta": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "sucesso",
              "erro"
            ]
          },
          "codigo": {
            "type": "string",
            "example": "CODIGO_PADRAO"
          },
          "mensagem": {
            "type": "string",
            "example": "Mensagem de retorno"
          }
        }
      },
      "ErroResponse": {
        "example": {
          "status": "erro",
          "codigo": "CODIGO_ERRO",
          "mensagem": "Descrição do erro"
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          }
        ]
      },
      "SucessoSimples": {
        "example": {
          "status": "sucesso",
          "codigo": "OPERACAO_SUCESSO",
          "mensagem": "Operação realizada com sucesso",
          "dados": {}
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          }
        ]
      },
      "LoginRequest": {
        "required": [
          "senha",
          "usuario"
        ],
        "type": "object",
        "properties": {
          "usuario": {
            "type": "string",
            "example": "joao"
          },
          "senha": {
            "type": "string",
            "format": "password",
            "example": "123"
          }
        }
      },
      "LoginResponse": {
        "example": {
          "status": "sucesso",
          "codigo": "LOGIN_SUCESSO",
          "mensagem": "Login realizado com sucesso",
          "dados": {
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
            "usuario": {
              "id": "1",
              "nome": "João",
              "email": "j@j.com"
            }
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          }
        ]
      },
      "CadastroRequest": {
        "required": [
          "email",
          "nome",
          "senha",
          "usuario"
        ],
        "type": "object",
        "properties": {
          "nome": {
            "type": "string",
            "example": "João da Silva"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "j@j.com"
          },
          "usuario": {
            "type": "string",
            "example": "joao"
          },
          "senha": {
            "type": "string",
            "format": "password",
            "example": "123"
          },
          "biografia": {
            "type": "string",
            "maxLength": 150,
            "example": "Minha bio aqui"
          },
          "foto": {
            "type": "string",
            "description": "Pode ser uma URL ou string Base64"
          }
        }
      },
      "CadastroResponse": {
        "example": {
          "status": "sucesso",
          "codigo": "USUARIO_CRIADO",
          "mensagem": "Usuário cadastrado com sucesso"
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          },
          {
            "type": "object",
            "properties": {
              "dados": {
                "$ref": "#/components/schemas/UsuarioSchema"
              }
            }
          }
        ]
      },
      "AtualizacaoRequest": {
        "type": "object",
        "properties": {
          "nome": {
            "type": "string",
            "example": "João da Silva"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "j@j.com"
          },
          "usuario": {
            "type": "string",
            "example": "joao"
          },
          "biografia": {
            "type": "string",
            "maxLength": 150
          },
          "foto": {
            "type": "string"
          },
          "senha": {
            "type": "string",
            "format": "password",
            "description": "Nova senha do usuário. Envie apenas se desejar alterá-la."
          }
        }
      },
      "AtualizacaoResponse": {
        "example": {
          "status": "sucesso",
          "codigo": "USUARIO_ATUALIZADO",
          "mensagem": "Usuário atualizado com sucesso",
          "dados": {
            "id": "1",
            "nome": "João",
            "email": "j@j.com",
            "usuario": "joao"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          }
        ]
      },
      "ListagemResponse": {
        "example": {
          "status": "sucesso",
          "codigo": "LISTAGEM_SUCESSO",
          "mensagem": "Usuários listados com sucesso",
          "dados": {
            "usuarios": [
              {
                "id": "1",
                "nome": "João",
                "email": "j@j.com",
                "usuario": "joao"
              }
            ]
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          }
        ]
      },
      "UsuarioSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "1"
          },
          "nome": {
            "type": "string",
            "example": "João da Silva"
          },
          "usuario": {
            "type": "string",
            "example": "joao"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "j@j.com"
          },
          "biografia": {
            "type": "string",
            "maxLength": 150,
            "example": "Desenvolvedor Java e entusiasta de astronomia."
          },
          "foto_url": {
            "type": "string",
            "format": "uri",
            "example": "https://api.projeto.com/fotos/joao.jpg"
          }
        }
      },
      "UsuarioUnicoResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/PadraoResposta"
          },
          {
            "type": "object",
            "properties": {
              "dados": {
                "$ref": "#/components/schemas/UsuarioSchema"
              }
            }
          }
        ],
        "example": {
          "status": "sucesso",
          "codigo": "USUARIO_ENCONTRADO",
          "mensagem": "Dados do usuário recuperados",
          "dados": {
            "id": "1",
            "nome": "João",
            "email": "j@j.com",
            "usuario": "joao",
            "biografia": "Desenvolvedor Java e entusiasta de astronomia."
          }
        }
      }
    },
    "securitySchemes": {
      "JWT": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
